# Generated by Django 5.2.12 on 2026-04-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_civil',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
    ]
